export const GET_INGREDIENTS = "GET_INGREDIENTS"
export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"

export const ERROR_EXIST = "ERROR_EXIST"
export const UPDATE_PURCHASE = "UPDATE_PURCHASE"
export const PURCHASE = "PURCHASE"
export const CANCEL_PURCHASE = "CANCEL_PURCHASE"
export const GET_ORDERS = "GET_ORDERS"
export const LOADING_START = "LOADING_START"
export const LOADING_OVER = "LOADING_OVER"





